### PR TITLE
Add lbfgs_strerror() to convert return codes into strings

### PR DESCRIPTION
**Pull request by jey**
Added a method to return a string description of LBFGS error codes to ease debugging and diagnosing failures.

### CODE REVIEW

**Comment by cynthia** [comment]
Thanks for the patch (and apologies for the delay), I'm a bit curious why the scope resolution operator was used as the notation considering that the library is C, and it makes it less obvious for non-C++ users. (e.g. Imagine if the string representation would be used to construct an exception from a downstream Could you elaborate on the rationale behind that?

**Comment by jey** [comment]
Good question. There's no particular rationale, other than that it seemed natural to me at the time because I was using C++. Feel free to change it.

**Comment by cynthia** [comment]
Thanks for the clarification. I’ll use the slightly more universal dot notation in that case. Thanks a lot for the patch, and apologies that this took so long!

**Comment by jey** [comment]
Actually, looks like the strings including `::` were taken directly from the libLBFGS documentation: http://www.chokkan.org/software/liblbfgs/group__liblbfgs__api.html#gga06fc87d81c62e9abb8790b6e5713c55ba5b92c84cf2dfd4bd5fc205afe385c940

Also, I would personally vote for scope resolution operator `::` over the member access operator `.`, because the use of `.` in `lbfgs_parameter_t.epsilon` is confusing since it's neither valid C nor C++ when `lbfgs_parameter_t` is a type-name. The meaning of `lbfgs_parameter_t::epsilon` is more unambiguous.

**Pull request merged**
