### PR TITLE
Bug was fixed in delta criterion

### PR DESCRIPTION
**Pull request by mikhailkin**
Delta criterion didn't work properly. Please, consider fix to add

### CODE REVIEW

**Comment by jey** [comment]
Interesting. Could you also provide a testcase that demonstrates the failure?

**Comment by yixuan** [comment]
Just encountered this bug. Indeed it should be fixed.

**Comment by jey** [comment]
@yixuan check out this fork which is actively maintained (and incorporates this patch): https://github.com/zc62/LBFGS

**Comment by yixuan** [comment]
Thanks @jey ! Also for your information, I have also translated this library into a header-only C++ version: https://github.com/yixuan/LBFGSpp.

**Comment by cynthia** [comment]
Apologies that this took so long. Landing now.

**Pull request merged**
