### PR TITLE
Enable build configuration with CMake

### PR DESCRIPTION
**Pull request by schuhschuh**
This PR adds a CMakeLists.txt configuration file for CMake. It makes use of a CMake module named `Subproject` that I wrote to be able to integrate libLBFGS directly into the source tree of another project using either `git submodule add` or `git subtree add`. At the same time, the very same CMake configuration file can be used to build libLBFGS as standalone library and install it following common conventions. A LBFGSConfig.cmake file is part of the installation which makes it easy for other projects that use CMake to link to this library.

### CODE REVIEW

**Comment by schuhschuh** [comment]
[Example of how to incorporate libLBFGS as subproject in existing CMake project.](https://github.com/BioMedIA/MIRTK/blob/bec5cbc9850666bf204f8ae05477f46276341136/CMake/Config/Depends.cmake#L72)

**Comment by giuliopaci** [comment]
Is there any reason why this pull request has not been merged?

**Comment by schuhschuh** [comment]
I'm afraid the reason may be that @chokkan is no longer actively maintaining this project. There hasn't been a commit to the master branch in 2 years, no response to issues...

**Comment by cynthia** [comment]
Apologies that this took so long. I've landed this in master now. Out of curiosity, would it also make sense to make this Hunter friendly now that Cmake support has landed?

**Pull request merged**
